import {el,link,section,tags} from '../utils';
import locationsText from '../data/locations.geojson?raw';
interface Entry {id:string;title:string;institution:string;period:string;description:string;locationId:string|null;tags:string[];impact?:string;tools?:string[];thesis?:string;project?:string;projectUrl?:string}
interface Place {type:'Feature';geometry:{type:'Point';coordinates:[number,number]};properties:{id:string;label:string;sourceUrl:string;verifiedAt:string}}
export function storySection(id:string,kicker:string,title:string,entries:Entry[]) {
  const node=section(id,kicker,title);node.classList.add('story-section');
  const grid=el('div','story-grid');const backdrop=el('aside','map-aside');const mapHost=el('div','map-host');mapHost.setAttribute('aria-label',`${id} map background`);const caption=el('p','map-caption');caption.setAttribute('aria-live','polite');backdrop.append(mapHost,caption);
  const timeline=el('div','timeline');grid.append(backdrop,timeline);node.append(grid);
  const places=(JSON.parse(locationsText) as {features:Place[]}).features.filter(p=>p.properties.sourceUrl&&p.properties.verifiedAt&&entries.some(x=>x.locationId===p.properties.id));
  let map:import('maplibre-gl').Map|undefined;let ready=false;let active=entries[0];
  function activate(entry:Entry){active=entry;timeline.querySelectorAll('article').forEach(x=>x.classList.toggle('active',x.id===`${id}-${entry.id}`));const place=places.find(p=>p.properties.id===entry.locationId);caption.textContent=place?place.properties.label:`${entry.institution} · regional context`;if(!map||!ready)return;map.stop();const camera={center:place?.geometry.coordinates||[-44,-20] as [number,number],zoom:place?12:3,padding:{top:40,bottom:65,left:matchMedia('(min-width: 801px)').matches?Math.min(innerWidth*.4,550):24,right:24}};if(matchMedia('(prefers-reduced-motion: reduce)').matches)map.jumpTo(camera);else map.flyTo({...camera,duration:1800,essential:false});}
  for(const entry of entries){const article=el('article','story-step');article.id=`${id}-${entry.id}`;article.append(el('p','eyebrow',entry.period),el('h3','',entry.title),el('p','institution',entry.institution),el('p','',entry.description));if(entry.thesis)article.append(el('p','thesis',`Thesis: ${entry.thesis}`));if(entry.project){article.append(el('p','thesis',`Project: ${entry.project}`));if(entry.projectUrl)article.append(link('View publication →',entry.projectUrl));}if(entry.tools?.length)article.append(el('p','tools',`Tools: ${entry.tools.join(' · ')}`));article.append(tags(entry.tags));if(entry.impact)article.append(el('p','impact',entry.impact));timeline.append(article);}
  activate(active);
  const observer=new IntersectionObserver(records=>{for(const record of records)if(record.isIntersecting){const entry=entries.find(x=>`${id}-${x.id}`===record.target.id);if(entry)activate(entry);}},{rootMargin:'-20% 0px -40% 0px'});timeline.querySelectorAll('article').forEach(x=>observer.observe(x));
  const lazy=new IntersectionObserver(async records=>{if(!records.some(x=>x.isIntersecting))return;lazy.disconnect();try{const {default:maplibre}=await import('../maps/map-engine');map=new maplibre.Map({container:mapHost,style:import.meta.env.VITE_MAP_STYLE_URL||{version:8,sources:{osm:{type:'raster',tiles:['https://tile.openstreetmap.org/{z}/{x}/{y}.png'],tileSize:256,maxzoom:19,attribution:'© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'}},layers:[{id:'osm',type:'raster',source:'osm',paint:{'raster-saturation':-.85,'raster-contrast':-.12,'raster-brightness-max':.98}}]},center:[-44,-20],zoom:3,scrollZoom:false,cooperativeGestures:true,attributionControl:{compact:true}});map.addControl(new maplibre.NavigationControl({showCompass:false}),'top-right');map.on('load',()=>{ready=true;for(const place of places)new maplibre.Marker({color:'#425e72'}).setLngLat(place.geometry.coordinates).addTo(map!);activate(active);});map.on('error',()=>{caption.textContent='Map unavailable. Continue exploring the timeline.';});new ResizeObserver(()=>{map?.resize();}).observe(mapHost);}catch{mapHost.append(el('p','map-fallback','Map unavailable on this device. All timeline entries are available below.'));}},{rootMargin:'400px'});lazy.observe(backdrop);return node;
}
